// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Numerics;

namespace data
{
    public class Order
    {
        public PizzaType? PizzaType { get; set; }
    }
}
