// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Numerics;

namespace data
{
    public enum PizzaType
    {
        DoughOnly = 0,
        Pineapple = 1,
    }
}
