// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using Flurl;
using Flurl.Http;
using System.Threading.Tasks;

namespace space
{
    public class PizzaController
    {
        private readonly FlurlClient client;
        public PizzaController(FlurlClient client) { this.client = client; }

        public async Task PizzaList(Page page)
        {
            await client.Request("/api/Pizza/PizzaList").GetAsync();
        }

        public async Task<Pizza> Get(Guid id)
        {
            return await client.Request("/api/Pizza/Get".SetQueryParam("id", id)).GetJsonAsync<Pizza>();
        }

        public async Task Order(Order order)
        {
            await client.Request("/api/Pizza/Order").PostJsonAsync(order);
        }

    }
}
